export const GET_PRODUCTS_BEGIN = "GET_PRODUCTS_BEGIN";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";

export const DELETE_PRODUCT_BEGIN = "DELETE_PRODUCT_BEGIN";

export const TOGGLE_PRODUCT = "TOGGLE_PRODUCT";

export const HANDLE_CHANGE = "HANDLE_CHANGE";

export const CREATE_PRODUCT_BEGIN = "CREATE_PRODUCT_BEGIN";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_ERROR = "CREATE_PRODUCT_ERROR";

export const CLEAR_VALUES = "CLEAR_VALUES";

export const CLEAR_ALERT = "CLEAR_ALERT";
